import type { TemplateDefinition } from "@tinykite/templates-base";

export const templatesBase: TemplateDefinition[] = [
  {
    id: "base-standard-cover",
    title: "Standard Cover",
    description: "Generic cover sheet template.",
    tags: ["base", "cover"],
    content: {
      headline: "Document Summary",
      footer: "Generated by Tinykite Tools"
    }
  }
];
