name: "Bug report"
description: "Report a bug with steps and expected behavior."
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "What happened?"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1. Go to..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What should have happened?"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "What actually happened?"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Browser, OS"
